# Generated by Django 4.0.3 on 2024-02-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('rollno', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=500)),
                ('s1_marks', models.FloatField()),
                ('s2_marks', models.FloatField()),
                ('avg_s_marks', models.FloatField()),
                ('i1_marks', models.FloatField()),
                ('i2_marks', models.FloatField()),
                ('avg_i_marks', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'ordering': ['rollno'],
            },
        ),
        migrations.CreateModel(
            name='StudentDBMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('rollno', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=500)),
                ('s1_marks', models.FloatField()),
                ('s2_marks', models.FloatField()),
                ('avg_s_marks', models.FloatField()),
                ('i1_marks', models.FloatField()),
                ('i2_marks', models.FloatField()),
                ('avg_i_marks', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'ordering': ['rollno'],
            },
        ),
        migrations.CreateModel(
            name='StudentETC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('rollno', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=500)),
                ('s1_marks', models.FloatField()),
                ('s2_marks', models.FloatField()),
                ('avg_s_marks', models.FloatField()),
                ('i1_marks', models.FloatField()),
                ('i2_marks', models.FloatField()),
                ('avg_i_marks', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'ordering': ['rollno'],
            },
        ),
        migrations.CreateModel(
            name='StudentFA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('rollno', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=500)),
                ('s1_marks', models.FloatField()),
                ('s2_marks', models.FloatField()),
                ('avg_s_marks', models.FloatField()),
                ('i1_marks', models.FloatField()),
                ('i2_marks', models.FloatField()),
                ('avg_i_marks', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'ordering': ['rollno'],
            },
        ),
        migrations.CreateModel(
            name='StudentM3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('rollno', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=500)),
                ('s1_marks', models.FloatField()),
                ('s2_marks', models.FloatField()),
                ('avg_s_marks', models.FloatField()),
                ('i1_marks', models.FloatField()),
                ('i2_marks', models.FloatField()),
                ('avg_i_marks', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'ordering': ['rollno'],
            },
        ),
        migrations.CreateModel(
            name='StudentOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('rollno', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=500)),
                ('s1_marks', models.FloatField()),
                ('s2_marks', models.FloatField()),
                ('avg_s_marks', models.FloatField()),
                ('i1_marks', models.FloatField()),
                ('i2_marks', models.FloatField()),
                ('avg_i_marks', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'ordering': ['rollno'],
            },
        ),
        migrations.CreateModel(
            name='StudentS_S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('rollno', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=500)),
                ('s1_marks', models.FloatField()),
                ('s2_marks', models.FloatField()),
                ('avg_s_marks', models.FloatField()),
                ('i1_marks', models.FloatField()),
                ('i2_marks', models.FloatField()),
                ('avg_i_marks', models.FloatField()),
                ('total', models.FloatField()),
            ],
            options={
                'ordering': ['rollno'],
            },
        ),
    ]
